# ## 14. Arrays de NumPy

NumPy es la biblioteca fundamental para computación científica en Python, proporcionando arrays multidimensionales eficientes y funciones matemáticas poderosas.

## 🎯 Resumen - ¿Por qué usar NumPy?

### ⚡ Eficiencia
- **Velocidad:** Manejo hasta 50 veces más rápido que las listas Python
- **Memoria:** Usan mucha menos memoria que las listas

### 📚 Sencillez de uso
- **Funciones matemáticas:** suma, resta, multiplicación, división, concatenación, etc.
- **Álgebra lineal:** descomposición LU, inversión de matrices, cálculo de determinantes, etc.
- **Indexación:** NumPy permite seleccionar subconjuntos de arrays de forma sencilla y eficiente

### 🔄 Versatilidad
- **Multidimensionalidad:** Arrays 1D, 2D, 3D, etc.
- **Compatibilidad:** Compatible con otras librerías (Pandas, SciPy, Matplotlib)

## 1️⃣ Importar NumPy y Crear Arrays

**Convención:** Importar NumPy como `np`

In [8]:
import numpy as np

# Crear array desde lista
arr1 = np.array([1, 2, 3, 4, 5])
print(f"Array 1D: {arr1}")
print(f"Tipo: {type(arr1)}")

# Array 2D (matriz)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\nArray 2D:\n{arr2}")

Array 1D: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>

Array 2D:
[[1 2 3]
 [4 5 6]]


In [9]:
# Funciones para crear arrays

# Array de ceros
ceros = np.zeros(5)
print(f"Ceros: {ceros}")

# Array de unos
unos = np.ones((2, 3))  # 2 filas, 3 columnas
print(f"\nUnos:\n{unos}")

# Rango de números
rango = np.arange(0, 10, 2)  # inicio, fin, paso
print(f"\nRango: {rango}")

# Espaciado lineal
linspace = np.linspace(0, 1, 5)  # 5 números entre 0 y 1
print(f"\nLinspace: {linspace}")

Ceros: [0. 0. 0. 0. 0.]

Unos:
[[1. 1. 1.]
 [1. 1. 1.]]

Rango: [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]


## 2️⃣ Propiedades de Arrays

| 📊 Propiedad | 📝 Descripción |
|---|---|
| `shape` | Dimensiones (filas, columnas) |
| `size` | Número total de elementos |
| `ndim` | Número de dimensiones |
| `dtype` | Tipo de datos |
| `dtype.name` | Nombre del tipo de datos |

In [10]:
# Crear array 2D
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

print(f"Array:\n{arr}\n")
print(f"Shape (forma):      {arr.shape}")  # (3, 4) = 3 filas, 4 columnas
print(f"Size (tamaño):      {arr.size}")   # 12 elementos
print(f"Ndim (dimensiones): {arr.ndim}")   # 2 dimensiones
print(f"Dtype (tipo):       {arr.dtype}")  # int64

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape (forma):      (3, 4)
Size (tamaño):      12
Ndim (dimensiones): 2
Dtype (tipo):       int64


## 3️⃣ Operaciones Matemáticas

NumPy realiza operaciones **elemento por elemento** (vectorización).

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Operaciones básicas
print(f"a = {a}")
print(f"b = {b}\n")

print(f"Suma:           a + b = {a + b}")
print(f"Resta:          a - b = {a - b}")
print(f"Multiplicación: a * b = {a * b}")
print(f"División:       b / a = {b / a}")
print(f"Potencia:       a ** 2 = {a ** 2}")

a = [1 2 3 4]
b = [10 20 30 40]

Suma:           a + b = [11 22 33 44]
Resta:          a - b = [ -9 -18 -27 -36]
Multiplicación: a * b = [ 10  40  90 160]
División:       b / a = [10. 10. 10. 10.]
Potencia:       a ** 2 = [ 1  4  9 16]


## 4️⃣ Indexación y Selección

Accede a elementos específicos del array usando índices.

In [12]:
# Acceso a elementos
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print(f"Array:\n{arr}\n")

# Elemento individual
print(f"arr[0, 1] = {arr[0, 1]}")  # Fila 0, columna 1 = 2

# Fila completa
print(f"Fila 1: arr[1] = {arr[1]}")

# Columna completa
print(f"Columna 1: arr[:, 1] = {arr[:, 1]}")

# Submatriz
print(f"Submatriz: arr[0:2, 1:3] = \n{arr[0:2, 1:3]}")

Array:
[[1 2 3]
 [4 5 6]]

arr[0, 1] = 2
Fila 1: arr[1] = [4 5 6]
Columna 1: arr[:, 1] = [2 5]
Submatriz: arr[0:2, 1:3] = 
[[2 3]
 [5 6]]


## 5️⃣ Funciones Estadísticas

NumPy proporciona funciones para análisis estadístico rápido.

In [13]:
datos = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(f"Datos: {datos}\n")

# Estadísticas
print(f"Suma:          {np.sum(datos)}")
print(f"Media:         {np.mean(datos)}")
print(f"Mediana:       {np.median(datos)}")
print(f"Desviación:    {np.std(datos):.2f}")
print(f"Mínimo:        {np.min(datos)}")
print(f"Máximo:        {np.max(datos)}")

Datos: [ 1  2  3  4  5  6  7  8  9 10]

Suma:          55
Media:         5.5
Mediana:       5.5
Desviación:    2.87
Mínimo:        1
Máximo:        10


## 6️⃣ Funciones de Álgebra Lineal

NumPy incluye funciones avanzadas para operaciones matriciales.

In [14]:
# Producto escalar
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

producto = np.dot(v1, v2)
print(f"Producto escalar: {v1} · {v2} = {producto}\n")

# Producto matricial
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.dot(A, B)
print(f"Producto matricial A·B:\n{C}\n")

# Inversa de matriz
A_inv = np.linalg.inv(A)
print(f"Inversa de A:\n{A_inv}\n")

# Determinante
det_A = np.linalg.det(A)
print(f"Determinante: {det_A:.2f}")

Producto escalar: [1 2 3] · [4 5 6] = 32

Producto matricial A·B:
[[19 22]
 [43 50]]

Inversa de A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Determinante: -2.00


## 📋 Conclusiones

NumPy es la base de la computación científica en Python. Sus principales ventajas son:

| ✨ Ventaja | 📝 Descripción |
|---|---|
| **Eficiencia** | 50x más rápido que listas Python, uso óptimo de memoria |
| **Vectorización** | Operaciones elemento por elemento sin bucles explícitos |
| **Multidimensionalidad** | Arrays 1D, 2D, 3D... sin complicaciones |
| **Funciones integradas** | Estadísticas, álgebra lineal, transformaciones |
| **Compatibilidad** | Compatible con Pandas, SciPy, Matplotlib, scikit-learn |

### 💡 Casos de uso típicos:
- 🔬 Análisis científico y cálculos matemáticos
- 📊 Procesamiento de datos y estadísticas
- 🤖 Machine Learning (junto con scikit-learn)
- 🖼️ Procesamiento de imágenes (con OpenCV, PIL)
- 📈 Visualización (con Matplotlib)

### 🎯 Próximos pasos:
- Aprender **Pandas** para manejo de datos estructurados (DataFrames)
- Explorar **SciPy** para funciones científicas avanzadas
- Practicar con datos reales y problemas del mundo real